# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=255)),
                ('ext', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Image'),
        ),
    ]
